# Generated by Django 5.1.2 on 2024-10-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите email', max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите ФИО', max_length=150, verbose_name='Ф.И.О')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Введите содержание письма', verbose_name='Тела письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_dispatch', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время первой отправки')),
                ('periodicity', models.IntegerField(choices=[(60, 'Раз в минуту'), (300, 'Раз в 5 минут'), (600, 'Раз в 10 минут'), (3600, 'Раз в час')], verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='created', max_length=15, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли рассылка')),
                ('next_send_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время следующей отправки')),
                ('last_send_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней отправки')),
                ('client', models.ManyToManyField(related_name='mailings', to='mailings.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailings.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('date_first_dispatch',),
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_dispatch', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('successfully', 'успешно'), ('fail', 'не успешно')], max_length=15, verbose_name='Статус попытки')),
                ('mail_service_response', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ почтового сервиса')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_attempts', to='mailings.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailings.mailings', verbose_name='Рассылки')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки:',
                'ordering': ('status',),
            },
        ),
    ]
