# Generated by Django 5.1.2 on 2024-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='date_first_dispatch',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первой отправки'),
        ),
    ]
