# Generated by Django 5.1.2 on 2024-10-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_attempts', to='mailings.client'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='client',
            field=models.ManyToManyField(related_name='mailings', to='mailings.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='created', max_length=15, verbose_name='Статус рассылки'),
        ),
    ]
