# Generated by Django 5.1.2 on 2024-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client_owner_mailings_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailings',
            options={'ordering': ('date_first_dispatch',), 'permissions': [('can_view_all_mailings', 'Can view all mailings'), ('can_view_users', 'Can view all users'), ('can_block_users', 'Can block users'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
