# Generated by Django 5.1.2 on 2024-10-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='client',
        ),
        migrations.AddField(
            model_name='mailings',
            name='clients',
            field=models.ManyToManyField(related_name='mailings', to='mailings.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_attempts', to='mailings.mailings', verbose_name='Рассылки'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailings.message', verbose_name='Сообщение'),
        ),
    ]
